DASM = /home/profs/aycock/599.82/bin/dasm
all:	test0.prg test1.prg test2.prg test3.prg test4.prg test5.prg test6.prg test7.prg test8.prg test9.prg test10.prg


test0.prg:	test0.s
		$(DASM) $< -o$@ -lout.lst

test1.prg:	test1.s
		$(DASM) $< -o$@ -lout.lst


test2.prg:	test2.s
		$(DASM) $< -o$@ -lout.lst


test3.prg:	test3.s
		$(DASM) $< -o$@ -lout.lst


test4.prg:	test4.s
		$(DASM) $< -o$@ -lout.lst


test5.prg:	test5.s
		$(DASM) $< -o$@ -lout.lst


test6.prg:	test6.s
		$(DASM) $< -o$@ -lout.lst


test7.prg:	test7.s
		$(DASM) $< -o$@ -lout.lst


test8.prg:	test8.s
		$(DASM) $< -o$@ -lout.lst


test9.prg:	test9.s
		$(DASM) $< -o$@ -lout.lst

test10.prg:	test10.s
		$(DASM) $< -o$@ -lout.lst